### ISSUE TITLE
Upon the lobby leader starting a round of Poker, I want to be able to receive my cards and the game is setup (3 cards on the table), so the game can start.

### ISSUE THREAD

**Issue by joelhube** [sopra-fs24-group-03/sopra-fs24-group-03-server#105]
Acceptance Criteria:
-Upon start of game/round , round is setup and users receive their card. 
-Table receives the cards.

Tasks Backend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#106
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#107
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#108
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#109
 
Tasks Frontend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#40
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#41
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#42
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#43
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#44
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#45
