### ISSUE TITLE
As a player, after I've completed my action, it is displayed for everyone so all players can follow the game.

### ISSUE THREAD

**Issue by joelhube** [sopra-fs24-group-03/sopra-fs24-group-03-server#116]
Acceptance Criteria:
-Display action for everyone.
-Turn is updated to next player.
-Check.

Tasks Backend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#117
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#118
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#119
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#120
- [x] #167
 
Tasks Frontend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#46
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#47
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#48
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#49
