### ISSUE TITLE
As a player if I have enough money I can call and bet the same amount as the previous player to remain in the game.

### ISSUE THREAD

**Issue by joelhube** [sopra-fs24-group-03/sopra-fs24-group-03-server#125]
Acceptance Criteria:
-Check if user has enough money.
-If enough money, user is able to click call button. Else not.
-The amount of the call is subtracted from the users Money and put into the pot.

Tasks Backend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#126
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#127

Tasks Frontend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#50
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#51
