### ISSUE TITLE
 As a player, I want to raise a specific amount of my money during the game, so I can influence the betting dynamics and potentially increase my winnings

### ISSUE THREAD

**Issue by joelhube** [sopra-fs24-group-03/sopra-fs24-group-03-server#130]
Acceptance Criteria:
-Click on raise button
-Enter amount to raise
-If amount <= my balance i can place the bet.

Tasks Backend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#131
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#132
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#133

Tasks Frontend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#52
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#53
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#54
