### ISSUE TITLE
As a player at the end of a round, I want to receive feedback indicating whether I won or lost the round (Winning Condition), so that I can understand the outcome of the game.

### ISSUE THREAD

**Issue by joelhube** [sopra-fs24-group-03/sopra-fs24-group-03-server#153]
Acceptance Criteria:
-End of a round is when 1. Everyone except 1 user folds or 2. All cards in the table are revealed.
-The cards of all players who are still in the game are displayed. The user with the best hand wins and receives the money in the pot.
-The winner is decided and receives money in the pot. All other users respectively loose the money they bet.

Tasks Backend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#154
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#155
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#156

Tasks Frontend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#62
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#63
