### ISSUE TITLE
As a player I want to be sent back to the lobby after the winning condition is checked So that I can prepare for the next game.

### ISSUE THREAD

**Issue by joelhube** [sopra-fs24-group-03/sopra-fs24-group-03-server#159]
Acceptance Criteria:
-Upon finish of a game of poker, all the users are sent to lobby overview
-There they can leave the game or stay in the lobby to play again.
-When the lobby leader clicks start game (<=2 and <=8 players) a new round starts

Tasks Backend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#160
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#161
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#162

Tasks Frontend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#64
