### ISSUE TITLE
As Player, I want to know, who won the game, to ensures clarity and providing a clear outcome.

### ISSUE THREAD

**Issue by joelhube** [sopra-fs24-group-03/sopra-fs24-group-03-server#170]
Acceptance Criteria:
-When a game is finished winning screen is displayed
-The cards of all Players who have not folded are checkt to know the winner

Task Backend:

- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#171
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#172
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#173
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#174
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#175
- [x] #232
- [x] #234

Task Frontend:

- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#69
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#83
