### ISSUE TITLE
As a lobby leader, I want be able to kick other players out of the Lobby so I can play only with the players I want.

### ISSUE THREAD

**Issue by joelhube** [sopra-fs24-group-03/sopra-fs24-group-03-server#177]
Acceptance Criteria:
-a lobby leader should be able to kick players which are not welcomed
-a kicked player is send to the home screen

Task Backend:

- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#178
- [x] #231

Task Frontend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#70
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#71
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#72
