### ISSUE TITLE
As a player, if I do not have enough money to play poker, I will receive a mark this is done to make the game more competitive.

### ISSUE THREAD

**Issue by joelhube** [sopra-fs24-group-03/sopra-fs24-group-03-server#182]
Acceptance Criteria:
-the marks of the users are after the game if necessary updated
-in the lobby the user can see how many marks the other users have
-in the home view the user can see how many marks he has

Task Backend:

- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#184
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#185
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#186
- [x] #233

Task Frontend:

- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#73
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#74
