### ISSUE TITLE
As a player, I want the small and big blinds to rotate by one after each round, so that fairness and equity are maintained throughout the game.

### ISSUE THREAD

**Issue by joelhube** [sopra-fs24-group-03/sopra-fs24-group-03-server#188]
Acceptance Criteria:
-when the game is finished the users in the list are rotated by one

Task Backend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#189
- [x] #207

Frontend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#75
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#76
