### ISSUE TITLE
As a user I want to change money for marks so I can get ride of my marks if I am playing good so that a user who is playing for a long time doesn't always gets more marks.

### ISSUE THREAD

**Issue by joelhube** [sopra-fs24-group-03/sopra-fs24-group-03-server#192]
Acceptance Criteria:
-user can trade money for marks

Task Backend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#193
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#194
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#195

Task Frontend:
- [ ] sopra-fs24-group-03/sopra-fs24-group-03-client#77
- [ ] sopra-fs24-group-03/sopra-fs24-group-03-client#78
- [ ] sopra-fs24-group-03/sopra-fs24-group-03-client#79

**Comment by N-oahh** [comment]
Not enough time to implement. Focus on more important features first
