### ISSUE TITLE
As a player I want to see the actions of the other players, to follow the game play.

### ISSUE THREAD

**Issue by joelhube** [sopra-fs24-group-03/sopra-fs24-group-03-server#199]
Acceptance Criteria:
-player can go all in
-when a player does an action all players see what action was done

Task Backend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#201
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#206
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#208
- [x] #229
- [x] #230

Task Frontend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#80
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#81
- [ ] sopra-fs24-group-03/sopra-fs24-group-03-client#82
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#84

**Comment by joelhube** [comment]
This userstory is complete there is no seperate all in button but you can go all in if you rais all your money. In our opinion this makes the frontend less overloaded and clearer.
