### ISSUE TITLE
As a player I want be able to go all in to be able to play a complet poker Game

### ISSUE THREAD

**Issue by joelhube** [sopra-fs24-group-03/sopra-fs24-group-03-server#214]
Acceptance Criteria:
- A player should be able to make an all in call
- The side pots are displayed so that players can follow the game

Tasks Backend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#215
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#216
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#217
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#218
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#219
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#220
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#221

Task Frontend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#87
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#88
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#89
