### ISSUE TITLE
As a logged in user I want be able to create a Lobby, to have my own Lobby where I am the lobbleader.

### ISSUE THREAD

**Issue by joelhube** [sopra-fs24-group-03/sopra-fs24-group-03-server#80]
Acceptance Criteria

-User that creates a lobby, he is the lobby leader.
-A lobby code is automatically generated.
-With this lobby code other user can join the lobby.
-The lobby leader can kick players out of the lobby.

Tasks Backend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#82
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#83
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#84
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#85

Tasks Frontend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#30
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#31
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#32
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#33
