### ISSUE TITLE
As a logged in user I want to be able to join a game/lobby, so that I can participate in gameplay with other users.

### ISSUE THREAD

**Issue by joelhube** [sopra-fs24-group-03/sopra-fs24-group-03-server#89]
Acceptance Criteria:
-A logged in user can click join game in home page. 
-Upon clicking join game he enters a game code.
-If code is correct/exists, he enter the lobby of the game.
-Is the code wrong the user gets an error and is directed back to the home page.

Tasks Backend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#90
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#91

Tasks Frontend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#34
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#35
