### ISSUE TITLE
As the lobby leader I want to be able to start a round of poker, so the game can be set up.

### ISSUE THREAD

**Issue by joelhube** [sopra-fs24-group-03/sopra-fs24-group-03-server#98]
Acceptance Criteria:
-The lobby leader can click on start button when <=2 and <=8 player are in the lobby.
-Only players with enough money can join the game.
-All players get redirected to game-screen.

Tasks Backend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#99
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#100
- [x] sopra-fs24-group-03/sopra-fs24-group-03-server#101

Tasks Frontend:
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#37
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#38
- [x] sopra-fs24-group-03/sopra-fs24-group-03-client#39
